export interface ProductInterface {
  id: number;
  name: string;
  description: string;
  price: number;
  imageUrl: string;
  category: string;
  rating: number;
  stock: number;
}

export const PRODUCTS: ProductInterface[] = [
  {
    id: 1,
    name: 'iPhone 14 Pro',
    description: 'Apple smartphone with 128GB storage, A16 Bionic chip.',
    price: 1199,
    imageUrl: 'https://placehold.co/300x300?text=iPhone+14+Pro',
    category: 'Mobiles',
    rating: 4.8,
    stock: 10,
  },
  {
    id: 2,
    name: 'Samsung Galaxy S23',
    description: 'Samsung flagship with dynamic AMOLED display.',
    price: 999,
    imageUrl: 'https://placehold.co/300x300?text=Galaxy+S23',
    category: 'Mobiles',
    rating: 4.6,
    stock: 12,
  },
  {
    id: 3,
    name: 'Redmi Note 12',
    description: 'Budget phone with powerful Snapdragon processor.',
    price: 299,
    imageUrl: 'https://placehold.co/300x300?text=Redmi+Note+12',
    category: 'Mobiles',
    rating: 4.2,
    stock: 30,
  },
  {
    id: 4,
    name: 'OnePlus Nord 3',
    description: 'Midrange phone with smooth Oxygen OS experience.',
    price: 399,
    imageUrl: 'https://placehold.co/300x300?text=Nord+3',
    category: 'Mobiles',
    rating: 4.4,
    stock: 18,
  },
  {
    id: 5,
    name: 'Butterfly Mixer Grinder',
    description: '750W kitchen mixer with 3 jars.',
    price: 89,
    imageUrl: 'https://placehold.co/300x300?text=Mixer+Grinder',
    category: 'Kitchen',
    rating: 4.1,
    stock: 22,
  },
  {
    id: 6,
    name: 'Prestige Pressure Cooker',
    description: '5L aluminum cooker for quick cooking.',
    price: 55,
    imageUrl: 'https://placehold.co/300x300?text=Pressure+Cooker',
    category: 'Kitchen',
    rating: 4.0,
    stock: 15,
  },
  {
    id: 7,
    name: 'Maybelline Fit Me Foundation',
    description: 'Matte + Poreless foundation for normal to oily skin.',
    price: 12,
    imageUrl: 'https://placehold.co/300x300?text=Fit+Me+Foundation',
    category: 'Makeup',
    rating: 4.5,
    stock: 40,
  },
  {
    id: 8,
    name: 'Lakme Eyeconic Kajal',
    description: 'Long-lasting waterproof kajal.',
    price: 4,
    imageUrl: 'https://placehold.co/300x300?text=Kajal',
    category: 'Makeup',
    rating: 4.3,
    stock: 50,
  },
  {
    id: 9,
    name: 'Nykaa Lipstick',
    description: 'Matte lipstick in various shades.',
    price: 8,
    imageUrl: 'https://placehold.co/300x300?text=Nykaa+Lipstick',
    category: 'Makeup',
    rating: 4.4,
    stock: 35,
  },
  {
    id: 10,
    name: 'Men\'s Denim Jacket',
    description: 'Blue denim jacket for men, regular fit.',
    price: 45,
    imageUrl: 'https://placehold.co/300x300?text=Denim+Jacket',
    category: 'Clothing',
    rating: 4.2,
    stock: 20,
  },
  {
    id: 11,
    name: 'Women\'s Kurti Set',
    description: 'Cotton kurti with palazzo pants.',
    price: 30,
    imageUrl: 'https://placehold.co/300x300?text=Kurti+Set',
    category: 'Clothing',
    rating: 4.5,
    stock: 25,
  },
  {
    id: 12,
    name: 'Boys Cotton T-Shirt',
    description: 'Cartoon printed round neck T-shirt.',
    price: 10,
    imageUrl: 'https://placehold.co/300x300?text=Kids+Tshirt',
    category: 'Clothing',
    rating: 4.3,
    stock: 50,
  },
  {
    id: 13,
    name: 'Mixer Juicer',
    description: '3-in-1 mixer juicer with 2-speed control.',
    price: 65,
    imageUrl: 'https://placehold.co/300x300?text=Mixer+Juicer',
    category: 'Kitchen',
    rating: 4.1,
    stock: 18,
  },
  {
    id: 14,
    name: 'Stainless Steel Cookware Set',
    description: '5-piece kitchen set for all cooking needs.',
    price: 99,
    imageUrl: 'https://placehold.co/300x300?text=Cookware+Set',
    category: 'Kitchen',
    rating: 4.6,
    stock: 16,
  },
  {
    id: 15,
    name: 'Smart LED TV 43"',
    description: 'Full HD Android Smart TV with voice remote.',
    price: 299,
    imageUrl: 'https://placehold.co/300x300?text=Smart+TV',
    category: 'Electronics',
    rating: 4.7,
    stock: 14,
  },
  {
    id: 16,
    name: 'Bluetooth Earbuds',
    description: 'TWS earbuds with noise cancellation.',
    price: 49,
    imageUrl: 'https://placehold.co/300x300?text=Earbuds',
    category: 'Electronics',
    rating: 4.2,
    stock: 28,
  },
  {
    id: 17,
    name: 'Fitness Smartwatch',
    description: 'Heart rate monitor, step counter, sleep tracker.',
    price: 59,
    imageUrl: 'https://placehold.co/300x300?text=Smartwatch',
    category: 'Electronics',
    rating: 4.3,
    stock: 19,
  },
  {
    id: 18,
    name: 'Digital Air Fryer',
    description: 'Low oil cooking with 5L capacity.',
    price: 85,
    imageUrl: 'https://placehold.co/300x300?text=Air+Fryer',
    category: 'Kitchen',
    rating: 4.6,
    stock: 11,
  },
  {
    id: 19,
    name: 'Men\'s Running Shoes',
    description: 'Comfortable shoes for sports and daily wear.',
    price: 40,
    imageUrl: 'https://placehold.co/300x300?text=Running+Shoes',
    category: 'Clothing',
    rating: 4.4,
    stock: 20,
  },
  {
    id: 20,
    name: 'Hair Dryer',
    description: 'Foldable compact hair dryer 1200W.',
    price: 22,
    imageUrl: 'https://placehold.co/300x300?text=Hair+Dryer',
    category: 'Electronics',
    rating: 4.1,
    stock: 30,
  },
  {
    id: 21,
    name: 'Cotton Bedsheet Set',
    description: 'Double bed bedsheet with 2 pillow covers.',
    price: 27,
    imageUrl: 'https://placehold.co/300x300?text=Bedsheet+Set',
    category: 'Home',
    rating: 4.0,
    stock: 24,
  },
  {
    id: 22,
    name: 'Electric Kettle',
    description: '1.5L fast boil electric kettle.',
    price: 25,
    imageUrl: 'https://placehold.co/300x300?text=Electric+Kettle',
    category: 'Kitchen',
    rating: 4.2,
    stock: 17,
  },
  {
    id: 23,
    name: 'Wall Clock',
    description: 'Modern design decorative wall clock.',
    price: 18,
    imageUrl: 'https://placehold.co/300x300?text=Wall+Clock',
    category: 'Home',
    rating: 4.3,
    stock: 29,
  },
  {
    id: 24,
    name: 'Water Bottle (1L)',
    description: 'Stainless steel insulated bottle.',
    price: 12,
    imageUrl: 'https://placehold.co/300x300?text=Water+Bottle',
    category: 'Home',
    rating: 4.5,
    stock: 36,
  },
  {
    id: 25,
    name: 'Makeup Brush Set',
    description: '10-piece soft bristle brushes for full face.',
    price: 20,
    imageUrl: 'https://placehold.co/300x300?text=Brush+Set',
    category: 'Makeup',
    rating: 4.4,
    stock: 40,
  }
]
